### ISSUE TITLE
v0.2/v0.3 过渡期 Roadmap

### ISSUE THREAD

**Issue by ilharp** [chrononeko/bugtracker#71]
为了保证 Chronocat 的版本间稳定性，一些原计划在 v0.3 中推出的功能将会提前至 v0.2.x 中实现或修复。

## v0.2.x

这些功能并不依赖 v0.3 的破坏性更改，因此决定将这些功能在 v0.2 内实现。

### v0.2.12

- [x] https://github.com/chrononeko/bugtracker/issues/66
- [x] https://github.com/chrononeko/bugtracker/issues/72

### v0.2.13

- [x] https://github.com/chrononeko/bugtracker/issues/74

### v0.2.15

- [x] https://github.com/chrononeko/bugtracker/issues/65

### v0.2.16

- [ ] https://github.com/chrononeko/bugtracker/issues/68
- [x] https://github.com/chrononeko/bugtracker/issues/76

## v0.3.0

这些功能包含破坏性更改，因此只能在 v0.3.0 版本中实现。

- [ ] https://github.com/chrononeko/bugtracker/issues/67
- [ ] https://github.com/chrononeko/bugtracker/issues/69
- [ ] https://github.com/chrononeko/bugtracker/issues/70

## v0.3.1

这些功能依赖 v0.3 功能但不含破坏性更改，为保证版本间稳定性，选择在 v0.3.1 中实现。

- [ ] https://github.com/chrononeko/bugtracker/issues/51
